{{- if.Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .Release.Name }}-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "external-dns.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
  - {}
  policyTypes:
  - Egress
{{- end }}
